### ISSUE TITLE
Remove pytest-pythonpath

### ISSUE THREAD

**Issue by dvzrv** [wemake-services/coverage-conditional-plugin#154]
Hi! When trying to package this project for Arch Linux I ran into the test requirement of [pytest-pythonpath](https://pypi.org/project/pytest-pythonpath/). With pytest >= 7.0.0 it seems not required anymore.

It would be awesome if the dependency for pytest could be updated and the requirement for pytest-pythonpath be removed.

**Comment by sobolevn** [comment]
Indeed, PR is welcome!
