### ISSUE TITLE
Add setuptools to requirements or use modern version to derive version

### ISSUE THREAD

**Issue by dvzrv** [wemake-services/coverage-conditional-plugin#174]
Currently, this plugin requires setuptools via [an import of pkg_resources](https://github.com/wemake-services/coverage-conditional-plugin/blob/a40c89224e0a293e8c366c28bb3b347285d18413/coverage_conditional_plugin/__init__.py#L7).
As setuptools is not necessarily installed on a target system, this requirement must be declared for this plugin, as it will fail otherwise.

Alternatively, it is possible to get version information from [importlib.metadata with python >= 3.8](https://docs.python.org/3.8/library/importlib.metadata.html) (e.g. by doing a fallback import in case you want to support python < 3.8).

**Comment by sobolevn** [comment]
PR is welcome

**Comment by sobolevn** [comment]
Both are fine :)

> Alternatively, it is possible to get version information from [importlib.metadata with python >= 3.8](https://docs.python.org/3.8/library/importlib.metadata.html) (e.g. by doing a fallback import in case you want to support python < 3.8).

But, I like this approach more! Example: https://github.com/wemake-services/flake8-eradicate/blob/363e4c83974bb01994bd302f5c0951c87e326d21/flake8_eradicate.py#L18-L21

**Comment by dvzrv** [comment]
Alright, I hope the PR is what you are looking for then! I'm also fixing #154 in there.

**Comment by dvzrv** [comment]
Ah, just now saw the import example. Will adapt the PR.
