### ISSUE TITLE
Can't get conditional pragmas to work

### ISSUE THREAD

**Issue by dosaki** [wemake-services/coverage-conditional-plugin#179]
I'm trying to work around #178 by running the tests by manually setting an `IS_INTEGRATION` variable.

This is my `.coveragerc` set up:
```
[run]
omit = *entrypoint*,*/tests/*

[coverage:run]
plugins =
  coverage_conditional_plugin

[coverage:report]
skip_empty = true
omit = *entrypoint*,*/tests/*

[coverage:coverage_conditional_plugin]
rules =
  "os_environ['IS_INTEGRATION'].lower()=='true'": integration
  "os_environ['IS_INTEGRATION'].lower()=='false'": unit
```

And this is how I've annotated some methods:
```pytest
    @classmethod
    def get(cls, value, joins=[]):  # pragma: integration
        primary_keys = cls.get_primary_key_names()
        if not primary_keys or len(primary_keys) < 1:
            return None

        result = cls.find_all_by(primary_keys[0], value, joins)
        try:
            return result[0]
        except:
            return None
```

However, when running with `IS_INTEGRATION='false'`, the method above is still flagged as uncovered:
![Screenshot 2022-09-26 at 11 16 30](https://user-images.githubusercontent.com/1957450/192252427-2a6f5902-d9e0-4507-96a4-069bb55afe2d.png)

**Comment by sobolevn** [comment]
Try switching `unit` and `integration`. Will it work?

**Comment by sobolevn** [comment]
Example: https://github.com/wemake-services/wemake-python-styleguide/blob/master/wemake_python_styleguide/compat/packaging.py#L5

**Comment by dosaki** [comment]
That makes sense! I guess I got confused reading the docs.
Thanks ❤️
