### ISSUE TITLE
Can't get this to work

### ISSUE THREAD

**Issue by pepoluan** [wemake-services/coverage-conditional-plugin#39]
So I have the following `.coveragerc`:

```
[run]
branch = true
parallel = true
plugins =
    coverage_conditional_plugin
omit =
     setup*
     aiosmtpd/testing/*
     aiosmtpd/tests/*
    .tox/*/lib/python3.*/site-packages/*
    .tox/*/Lib/site-packages/*
    .tox/Lib/site-packages/*
    .tox/*/site-packages/*

[paths]
source =
    aiosmtpd

[report]
exclude_lines =
    pragma: nocover
    pragma: no${PLATFORM}

[coverage_conditional_plugin]
rules =
    "sys_version_info >= (3, 9)": py-gte-39
    "sys_version_info < (3, 9)": py-lt-39
```

And have the following code:

```python
    def _stop(self):
        self.loop.stop()
        try:  # pragma: py-lt-39
            _all_tasks = asyncio.Task.all_tasks
        except AttributeError:  # pragma: py-gte-39
            _all_tasks = asyncio.all_tasks
        for task in _all_tasks(self.loop):
            task.cancel()
```

It still resulted in < 100% coverage for Python < 3.9

Where did I go wrong?

**Comment by sobolevn** [comment]
Can please create a reproduction repo for me to test?

In the meantime, here's a working example: https://github.com/wemake-services/wemake-python-styleguide

**Comment by pepoluan** [comment]
Hi, this is the repo with changes to `tox.ini` and `.coveragerc`:

https://github.com/pepoluan/aiosmtpd/tree/auth_39

**Comment by sobolevn** [comment]
@pepoluan can you please create a simple reproduceable example for me?
1. I was not able to find build jobs for the given repo
2. I am not sure which line is which: `_all_tasks = asyncio.Task.all_tasks` is it for python3.9+? Or for previous versions?
3. The repo is huge on its own: I am not sure how coverage is calculated and what is included and what is not

**Comment by pepoluan** [comment]
Yeah, the issue was only with the [controller.py](https://github.com/pepoluan/aiosmtpd/blob/auth_39/aiosmtpd/controller.py) file.

Python 3.9 removes `_all_tasks = asyncio.Task.all_tasks`; the same function now only exists as `asyncio.all_tasks`. So on Python <= 3.9, the line `_all_tasks = asyncio.all_tasks` should not be test for coverage.

```python
        try:
            _all_tasks = asyncio.Task.all_tasks  # this will fail on Python 3.9
        except AttributeError:  # this will trigger *only* on Python 3.9
            _all_tasks = asyncio.all_tasks  # this line will never be reached on Python < 3.9
```

**Comment by pepoluan** [comment]
Revisiting this, now conditional pragma's work.

Not sure if that's due to a change of this plugin or a change on my side.

Anyways, since it works, I can no longer reproduce this error, and thus this issue can be closed.
