### ISSUE TITLE
Compatibility to Python 3.9

### ISSUE THREAD

**Issue by pepoluan** [wemake-services/coverage-conditional-plugin#40]
A reminder issue from [this comment on StackOverflow](https://stackoverflow.com/questions/35513257/can-python-coverage-module-conditionally-ignore-lines-in-a-unit-test/63852990?noredirect=1#comment113698857_63852990)

**Comment by sobolevn** [comment]
Thanks! We are blocked by https://github.com/wemake-services/wemake-python-styleguide/milestone/18

**Comment by pepoluan** [comment]
Seems to be working now on Python 3.9
