### ISSUE TITLE
coverage-conditional-plugin 0.3.1 has requirement packaging<21.0,>=20.4, but you have packaging 21.0

### ISSUE THREAD

**Issue by mborsetti** [wemake-services/coverage-conditional-plugin#90]
Please support current package releases and/or remove overly restrictive requirements (i.e. only use `>=`)!

**Comment by sobolevn** [comment]
Will fix it today! Thanks!

**Comment by sobolevn** [comment]
Done in `0.4.0`! Thanks for your bug report! 🎉 

Please, feel free to reopen if it does not solve your problem.
